object Versions {
    const val android = "8.2.1"
    const val kotlin = "1.9.22"
    const val compose = "1.5.1"
    const val composeDestinations = "1.9.62"
    const val composeLifecycle = "2.6.2"
    const val composeViewModel = "2.7.0"
    const val kspPlugin = "1.9.22-1.0.17"
    const val activityCompose = "1.8.2"
    const val composeMaterial3 = "1.1.2"
    const val room_version = "2.5.0"
    const val hilt_version = "2.48"
    const val hilt_compose_navigation = "1.1.0"
    const val retrofit_version = "2.9.0"
    const val okHttp_version = "5.0.0-alpha.2"
    const val datastore = "1.0.0"
    const val junit = "4.13.2"
    const val junitTest = "1.1.5"
    const val espresso = "3.5.1"

}